image: pdschbrt/phasar-build-environment:latest

stages:
  - build

# install the necessary build tools
before_script:
  - git submodule update --init --recursive

build:
  stage: build
  # build all interesting targets
  script:
    - mkdir -p build
    - cd build
    - echo "checking RAM"
    - cat /proc/meminfo
    - echo "checking CPU(s)"
    - cat /proc/cpuinfo
    - CC=clang CXX=clang++ cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DPHASAR_BUILD_UNITTESTS=ON -G Ninja ..
    - ninja
# Install Phasar and test the examples
    - make install
    - cd /builds/pdschbrt/sse_dfa_llvm/examples/llvm-hello_world/
    - make all
    - cd /builds/pdschbrt/sse_dfa_llvm/examples/plugins/
    - make all
    # Jump back to save the artifacts
    - cd /builds/pdschbrt/sse_dfa_llvm/build
  only:
    - master
    - development
    - variability
  tags:
    - shared
  # save the documentation and binary
  artifacts:
    name: "PhASAR-$CI_BUILD_ID-$CI_BUILD_REF"
    expire_in: 1 week
    paths:
      - build/
  # depending on the build setup it's a good idea to cache outputs to reduce the build time
  cache:
    paths:
      - build/lib/
